CREATE USER username1;
ALTER USER username1 WITH PASSWORD 'mypassword';
GRANT ALL PRIVILEGES ON DATABASE "NewBase" to username1;
create table MOCK_DATA	 (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20)
);
CREATE USER admin WITH PASSWORD 'mypassword1';
CREATE USER username2 WITH PASSWORD 'mypassword2';
GRANT ALL PRIVILEGES ON TABLE "drivers" to admin;
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (1, 'Lezlie', 'Pietzker', 'lpietzker0@deviantart.com', 'Female', '95.13.37.197');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (2, 'Artemus', 'Burkitt', 'aburkitt1@about.me', 'Male', '130.166.23.204');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (3, 'Rene', 'Borges', 'rborges2@storify.com', 'Polygender', '23.55.117.241');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (4, 'Karalynn', 'Harbard', 'kharbard3@youku.com', 'Polygender', '38.218.208.129');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (5, 'Angie', 'Warwick', 'awarwick4@mtv.com', 'Polygender', '81.166.229.179');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (6, 'Chaddy', 'Yankishin', 'cyankishin5@hhs.gov', 'Female', '32.15.214.226');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (7, 'Martino', 'Headingham', 'mheadingham6@fastcompany.com', 'Polygender', '105.172.197.250');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (8, 'Gary', 'Oliffe', 'goliffe7@marketwatch.com', 'Non-binary', '108.91.222.235');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (9, 'Ailee', 'Scannell', 'ascannell8@cbslocal.com', 'Genderfluid', '205.29.4.153');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (10, 'Fraser', 'Desporte', 'fdesporte9@loc.gov', 'Male', '177.9.12.156');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (11, 'Levin', 'Purdon', 'lpurdona@sohu.com', 'Agender', '170.121.214.113');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (12, 'Sibilla', 'Clemoes', 'sclemoesb@clickbank.net', 'Non-binary', '187.185.187.118');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (13, 'Leah', 'Levay', 'llevayc@youku.com', 'Genderqueer', '28.156.100.30');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (14, 'Sheilakathryn', 'Doncaster', 'sdoncasterd@addthis.com', 'Male', '146.104.201.137');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (15, 'Oneida', 'Lytle', 'olytlee@washingtonpost.com', 'Agender', '214.229.255.227');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (16, 'Binky', 'Skewes', 'bskewesf@hugedomains.com', 'Non-binary', '172.35.199.230');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (17, 'Mignon', 'Raynes', 'mraynesg@devhub.com', 'Polygender', '56.213.152.14');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (18, 'Enrika', 'Sybbe', 'esybbeh@gov.uk', 'Genderqueer', '197.135.195.176');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (19, 'Farand', 'Matteini', 'fmatteinii@cpanel.net', 'Male', '125.103.219.54');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (20, 'Sutherland', 'Spacey', 'sspaceyj@reference.com', 'Bigender', '217.183.121.203');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (21, 'Kennedy', 'Mompesson', 'kmompessonk@eepurl.com', 'Non-binary', '185.199.24.140');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (22, 'Christophe', 'Scarratt', 'cscarrattl@java.com', 'Polygender', '152.37.128.63');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (23, 'Wanda', 'Randerson', 'wrandersonm@list-manage.com', 'Genderqueer', '7.235.45.0');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (24, 'Malynda', 'Godsell', 'mgodselln@tinypic.com', 'Non-binary', '235.204.247.13');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (25, 'Alexine', 'Heatherington', 'aheatheringtono@xrea.com', 'Polygender', '151.20.253.190');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (26, 'Matthus', 'Winspeare', 'mwinspearep@youtu.be', 'Agender', '26.69.68.35');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (27, 'Garner', 'McKellen', 'gmckellenq@goo.gl', 'Bigender', '139.181.232.194');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (28, 'Maurice', 'Fussen', 'mfussenr@sfgate.com', 'Genderqueer', '165.86.78.66');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (29, 'Knox', 'Elijah', 'kelijahs@trellian.com', 'Agender', '45.27.126.159');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (30, 'Aldon', 'Hardaker', 'ahardakert@altervista.org', 'Non-binary', '52.117.180.245');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (31, 'Gaby', 'Jancy', 'gjancyu@springer.com', 'Male', '141.81.126.215');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (32, 'Margeaux', 'Jahan', 'mjahanv@odnoklassniki.ru', 'Bigender', '135.144.93.117');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (33, 'Gipsy', 'Jerred', 'gjerredw@booking.com', 'Genderqueer', '92.237.205.150');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (34, 'Joela', 'Cokely', 'jcokelyx@dell.com', 'Agender', '76.116.152.242');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (35, 'Chauncey', 'Domegan', 'cdomegany@weebly.com', 'Genderfluid', '146.161.73.6');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (36, 'Lisetta', 'Aleksankov', 'laleksankovz@answers.com', 'Male', '246.66.44.1');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (37, 'Mitchel', 'Heather', 'mheather10@chronoengine.com', 'Non-binary', '5.201.231.49');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (38, 'Brear', 'Hancill', 'bhancill11@digg.com', 'Genderfluid', '39.84.198.2');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (39, 'Cherish', 'Lapidus', 'clapidus12@geocities.jp', 'Polygender', '53.17.109.220');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (40, 'Sibby', 'Waitland', 'swaitland13@51.la', 'Polygender', '147.40.48.4');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (41, 'Hesther', 'Aggas', 'haggas14@infoseek.co.jp', 'Bigender', '4.157.136.142');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (42, 'Malchy', 'Klasing', 'mklasing15@unesco.org', 'Polygender', '109.244.107.228');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (43, 'Grove', 'Oxenbury', 'goxenbury16@google.com.br', 'Male', '66.153.124.191');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (44, 'Ernie', 'Forrestor', 'eforrestor17@tripod.com', 'Genderfluid', '57.8.210.192');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (45, 'Jillane', 'Silber', 'jsilber18@cafepress.com', 'Non-binary', '26.152.173.164');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (46, 'Clementine', 'Swatten', 'cswatten19@usgs.gov', 'Non-binary', '254.8.165.241');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (47, 'Emanuele', 'Gawkes', 'egawkes1a@ucsd.edu', 'Genderqueer', '188.44.13.251');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (48, 'Tonia', 'Elvin', 'telvin1b@rakuten.co.jp', 'Polygender', '156.19.141.111');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (49, 'Rosabella', 'Naire', 'rnaire1c@com.com', 'Polygender', '51.76.82.135');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (50, 'Wynn', 'Winskill', 'wwinskill1d@arstechnica.com', 'Polygender', '143.30.130.89');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (51, 'Corly', 'Ketton', 'cketton1e@ask.com', 'Genderqueer', '185.54.247.221');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (52, 'Marjy', 'Tilberry', 'mtilberry1f@cdbaby.com', 'Genderqueer', '239.7.16.179');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (53, 'Marilin', 'Marston', 'mmarston1g@weibo.com', 'Polygender', '131.78.162.60');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (54, 'Llywellyn', 'Iorns', 'liorns1h@earthlink.net', 'Female', '108.21.50.124');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (55, 'Jaymee', 'Cypler', 'jcypler1i@de.vu', 'Genderqueer', '13.110.120.170');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (56, 'Mehetabel', 'Card', 'mcard1j@flavors.me', 'Non-binary', '201.153.90.186');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (57, 'Pail', 'Hollyar', 'phollyar1k@bigcartel.com', 'Male', '126.133.219.164');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (58, 'Eileen', 'Skullet', 'eskullet1l@apple.com', 'Male', '192.94.165.186');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (59, 'Blondelle', 'Loughton', 'bloughton1m@cdc.gov', 'Genderqueer', '61.232.206.9');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (60, 'Kristen', 'Rhoddie', 'krhoddie1n@comcast.net', 'Genderfluid', '165.143.201.27');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (61, 'Michaela', 'Rown', 'mrown1o@google.de', 'Agender', '40.55.27.34');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (62, 'Philbert', 'Beaney', 'pbeaney1p@pbs.org', 'Bigender', '33.244.184.210');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (63, 'Timmi', 'Stonhewer', 'tstonhewer1q@mapy.cz', 'Agender', '125.255.5.26');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (64, 'Morganica', 'McGourty', 'mmcgourty1r@walmart.com', 'Genderqueer', '230.206.248.229');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (65, 'Mireielle', 'Bizley', 'mbizley1s@miitbeian.gov.cn', 'Bigender', '51.32.133.115');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (66, 'Jarrid', 'Devenny', 'jdevenny1t@reuters.com', 'Male', '226.166.178.55');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (67, 'Roxanne', 'Chaloner', 'rchaloner1u@wufoo.com', 'Female', '57.114.204.166');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (68, 'Dyann', 'Bartoszewski', 'dbartoszewski1v@cnn.com', 'Female', '44.184.132.13');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (69, 'Elfrida', 'Mollon', 'emollon1w@ezinearticles.com', 'Bigender', '122.69.253.136');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (70, 'Devlen', 'Tippler', 'dtippler1x@unc.edu', 'Genderqueer', '82.233.47.2');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (71, 'Gladys', 'Shavel', 'gshavel1y@cmu.edu', 'Polygender', '119.87.227.131');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (72, 'Stephenie', 'Tilte', 'stilte1z@free.fr', 'Bigender', '119.178.150.236');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (73, 'Marilee', 'Murrison', 'mmurrison20@instagram.com', 'Polygender', '87.39.214.156');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (74, 'Merla', 'Maidlow', 'mmaidlow21@trellian.com', 'Agender', '94.210.33.123');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (75, 'Justin', 'Anyon', 'janyon22@google.cn', 'Agender', '176.98.195.73');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (76, 'Wayland', 'Fearon', 'wfearon23@nytimes.com', 'Non-binary', '154.73.158.42');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (77, 'Karena', 'Geraldi', 'kgeraldi24@prweb.com', 'Male', '250.109.209.250');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (78, 'Aggi', 'Karp', 'akarp25@baidu.com', 'Male', '100.34.139.109');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (79, 'Dom', 'Hostan', 'dhostan26@google.co.uk', 'Male', '77.238.120.176');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (80, 'Jermain', 'Christoffe', 'jchristoffe27@symantec.com', 'Bigender', '49.95.206.242');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (81, 'Marigold', 'Lapides', 'mlapides28@dailymotion.com', 'Bigender', '235.41.91.187');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (82, 'Cherie', 'Mac Giany', 'cmacgiany29@weather.com', 'Bigender', '114.239.36.110');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (83, 'Libbie', 'Fry', 'lfry2a@ucoz.com', 'Agender', '51.124.250.138');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (84, 'Chelsy', 'Quince', 'cquince2b@devhub.com', 'Genderfluid', '197.104.98.165');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (85, 'Arman', 'Brownfield', 'abrownfield2c@uol.com.br', 'Female', '144.20.19.223');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (86, 'Scarlet', 'Crohan', 'scrohan2d@vk.com', 'Genderfluid', '173.126.70.99');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (87, 'Franciska', 'Coady', 'fcoady2e@vkontakte.ru', 'Male', '150.161.223.199');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (88, 'Delphinia', 'Cowpe', 'dcowpe2f@istockphoto.com', 'Non-binary', '152.211.169.111');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (89, 'Courtnay', 'Linnit', 'clinnit2g@nationalgeographic.com', 'Bigender', '36.22.236.159');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (90, 'Flynn', 'Lexa', 'flexa2h@arizona.edu', 'Male', '141.96.134.124');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (91, 'Debra', 'Sandifer', 'dsandifer2i@deviantart.com', 'Non-binary', '151.159.147.137');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (92, 'Nap', 'Kalderon', 'nkalderon2j@example.com', 'Male', '254.1.109.79');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (93, 'Gabi', 'Roscam', 'groscam2k@boston.com', 'Female', '192.171.221.120');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (94, 'Dewey', 'MacEnelly', 'dmacenelly2l@mozilla.org', 'Bigender', '130.114.99.97');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (95, 'Karita', 'Murra', 'kmurra2m@census.gov', 'Polygender', '19.159.23.186');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (96, 'Johnnie', 'Brinsden', 'jbrinsden2n@ameblo.jp', 'Polygender', '96.49.209.83');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (97, 'Delano', 'Merrison', 'dmerrison2o@twitpic.com', 'Genderfluid', '10.51.230.98');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (98, 'Tabby', 'Bushe', 'tbushe2p@1und1.de', 'Female', '87.89.49.219');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (99, 'Desmond', 'Bastard', 'dbastard2q@ifeng.com', 'Agender', '191.41.35.91');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (100, 'Jerry', 'Wale', 'jwale2r@chron.com', 'Non-binary', '65.199.127.46');